//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string Reg_no { get; set; }
        public string St_firstName { get; set; }
        public string St_middlename { get; set; }
        public string St_lastname { get; set; }
        public string Fathername { get; set; }
        public string Session { get; set; }
        public string Section { get; set; }
        public string Discipline { get; set; }
        public string Gender { get; set; }
        public string Semester { get; set; }
    }
}
